apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: custom-appset
spec:
  generators:
    - list:
        elements:
          - name: feature-a
- name: feature-b
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/np123-glitch/tambolaplayer
        targetRevision: main
        path: charts/{{name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
