name: Generate ApplicationSet
on:
  workflow_dispatch:
    inputs:
      features:
        description: "Select Features (comma-separated: Software Hub, IKC, DataStage, Awesomeness)"
        required: true
      namespace:
        description: "Enter Kubernetes Namespace"
        required: true
        default: "default"

jobs:
  generate-appset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse Features
        id: parse
        run: |
          echo "Selected Features: ${{ github.event.inputs.features }}"
          FEATURES=$(echo "${{ github.event.inputs.features }}" | tr ',' ' ')
          echo "FEATURES=$FEATURES" >> $GITHUB_ENV
          echo "NAMESPACE=${{ github.event.inputs.namespace }}" >> $GITHUB_ENV

      - name: Generate ApplicationSet YAML
        run: |
          cat <<EOF > application-set.yaml
          apiVersion: argoproj.io/v1alpha1
          kind: ApplicationSet
          metadata:
            name: custom-appset
          spec:
            generators:
              - list:
                  elements:
                    $(for feature in $FEATURES; do echo "- name: $feature"; done)
            template:
              metadata:
                name: '{{name}}'
              spec:
                project: default
                source:
                  repoURL: https://github.com/${{ github.repository }}
                  targetRevision: main
                  path: charts/{{name}}
                destination:
                  server: https://kubernetes.default.svc
                  namespace: "${{ github.event.inputs.namespace }}"
                syncPolicy:
                  automated:
                    prune: true
                    selfHeal: true
          EOF

      - name: Upload ApplicationSet YAML as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-set
          path: application-set.yaml

      - name: Commit ApplicationSet to Repository (Optional)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated ApplicationSet"
          file_pattern: "application-set.yaml"
